name = "GaussianFreeFields"                                                                                  
uuid = "8aaff5dd-7728-4910-872e-58ea0ac23ce0"                                                                      
version = "0.1.0"                                                                                                  
